import type { Metadata } from "next";
import "./globals.css";
import { StoreHydration } from "@/Hooks/useHydration";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   // className="min-h-screen overflow-x-hidden"
   return (
      <html>
         <body>
            <StoreHydration />
            {children}
         </body>
      </html>
   );
}
